#!/bin/bash

BUILD_OPTION=PRODUCTION
BUILD_OPTION_SET=false

while [ -n "$1" ]
do
    case "$1" in

        -b | --build-option)
            BUILD_OPTION="$2"
            BUILD_OPTION_SET=true
            shift
            ;;
    esac

    # We're done with the current argument, move to the next.
    shift
done

view-default

# Set build options
cd /vobs/lasrs++/Dds/redist
build-default
build-ddsimplementation RTI_CONNEXT
build-buildoption "$BUILD_OPTION"

# Actually run the build
make -B
