#!/bin/bash

# Set toolbox build options
cd /vobs/toolbox++
build-default
build-buildoption PRODUCTION

# Set DDS redistributable build options
cd /vobs/lasrs++/Dds/redist
build-default
build-buildoption PRODUCTION
build-ddsimplementation OPEN_SPLICE

# Actually run the build
cd /vobs/UAV/DdsNode
make -B ddsnode
