#!/bin/bash

BUILD_OPTION=PRODUCTION
BUILD_OPTION_SET=false

while [ -n "$1" ]
do
    case "$1" in

        -b | --build-option)
            BUILD_OPTION="$2"
            BUILD_OPTION_SET=true
            shift
            ;;
    esac

    # We're done with the current argument, move to the next.
    shift
done

# Set toolbox build options
cd /vobs/toolbox++
build-default
build-buildoption "$BUILD_OPTION"

# Set DDS redistributable build options
cd /vobs/lasrs++/Dds/redist
build-default
build-ddsimplementation OPEN_SPLICE
build-buildoption "$BUILD_OPTION"

# Actually run the build
cd /vobs/UAV/DdsNode
make -B ddsnode
