#!/bin/bash

# Set build options
cd /vobs/aircraft++
build-default
build-models genericuav
build-plugins serialportparser matlab2010a
build-buildoption PRODUCTION

# Actually run the build
clearmake -B ~/.bldhost.jedi.ndc.nasa.gov -V sim
