#!/bin/tcsh

# Reset this view back to default; gets rid of all view-private files, among
# other things
view-default

# Set build options
cd /vobs/aircraft++
build-default
build-models humanobserver
build-plugins serialportparser
build-buildoption PRODUCTION

# Actually run the build
kw-nightly HumanObserver "clearmake -B ~/.bldhost.jedi.ndc.nasa.gov -V sim"
kw-sync HumanObserver LaSRS_Core
