#!/bin/bash

# Set build options
cd /vobs/aircraft++
build-default
build-models humanobserver
build-plugins serialportparser
build-buildoption PRODUCTION

# Actually run the build
clearmake -B ~/.bldhost.jedi.ndc.nasa.gov -V sim
