#!/bin/bash

# cleartool setcs won't take a stream so the default cs has to go to a file first
TMP_CS=/tmp/$USER.cs

if [ -z "$1" ]; then
    echo "What branch should I remove?"
    exit
fi

cleartool catcs | grep -v $1 > $TMP_CS

cleartool setcs $TMP_CS
