#!/bin/bash

TYPE=
TYPE_SET=false

NAME=
NAME_SET=false

INITFILENAME=
INITFILENAME_SET=false

INITCASENUMBER=
INITCASENUMBER_SET=false

DISPLAYTYPE=
DISPLAYTYPE_SET=false

while [ -n "$1" ]
do
    case "$1" in
	--name)
	    NAME=$2
	    NAME_SET=true
	    shift
	    ;;

	--initfilename)
	    INITFILENAME=$2
	    INITFILENAME_SET=true
	    shift
	    ;;

	--initcasenumber)
	    INITCASENUMBER=$2
	    INITCASENUMBER_SET=true
	    shift
	    ;;

	--displaytype)
	    DISPLAYTYPE=$2
	    DISPLAYTYPE_SET=true
	    shift
	    ;;

	*)
	    if [ "$TYPE_SET" = "true" ]; then
		echo "Specify only a single type" 1>&2
		exit 1
	    fi

	    TYPE=$1
	    TYPE_SET=true
	    ;;
    esac

    # We're done with the current argument, move to the next.
    shift
done

if [ "$TYPE_SET" = "false" ]; then
    echo "You must specify a type" 1>&2
    exit 1
fi

printf "  Begin_PositionalModel\n"
printf "    Type $TYPE\n"

if [ "$NAME_SET" = "true" ]; then
    printf "    Name $NAME\n"
else
    printf "    Name $TYPE\n"
fi

if [ "$INITFILENAME_SET" = "true" ]; then
    printf "    InitFileName $INITFILENAME\n"
fi

if [ "$INITCASENUMBER_SET" = "true" ]; then
    printf "    InitCaseNumber $INITCASENUMBER\n"
fi

if [ "$DISPLAYTYPE_SET" = "true" ]; then
    printf "    DisplayType $DISPLAYTYPE\n"
fi

printf "    Begin_Hardware\n"
printf "    End_Hardware\n"
printf "  End_PositionalModel\n"

exit 0