#!/bin/bash
# Prints added, deleted, and modified files over the specified commit range

COMMIT_RANGE="HEAD~1.."

while [ -n "$1" ]
do
    case "$1" in
        *)
            COMMIT_RANGE="$1"
            break;
            ;;

    esac

    # We're done with the current argument, move to the next.
    shift
done

echo "Added:"
git diff --diff-filter=A --name-only "${COMMIT_RANGE}"
echo ""

echo "Deleted:"
git diff --diff-filter=D --name-only "${COMMIT_RANGE}"
echo ""

echo "Modified:"
git diff --diff-filter=CMRTUXB --name-only "${COMMIT_RANGE}"
