#!/bin/sh -e

# Prints added, deleted, and modified files over the specified commit range

COMMIT_RANGE="HEAD~1.."
if [ "${1}" ]; then
    COMMIT_RANGE="${1}"
fi

echo "Added:"
git diff --diff-filter=A --name-only "${COMMIT_RANGE}"
echo ""

echo "Deleted:"
git diff --diff-filter=D --name-only "${COMMIT_RANGE}"
echo ""

echo "Modified:"
git diff --diff-filter=CMRTUXB --name-only "${COMMIT_RANGE}"
