#!/bin/bash

if [ -z "$1" ]; then
    echo "Which view should I nuke?"
    exit
fi

# Blow away the view storage directory
echo "Removing storage directory"
rm -rf /net/jedi.ndc.nasa.gov/viewstore/$USER/$1.vws

# Unregister the view
echo "Unregistering view"
UUID=`cleartool lsview -long $1 | grep "View uuid" | cut -d " " -f 3`
cleartool unregister -view -uuid $UUID

# Remove the view tag
echo "Removing view tag"
cleartool rmtag -view $1
