#!/bin/bash

SRC="/var/lib/plexmediaserver/Library/Application Support/Plex Media Server"
DST="/mnt/raid/Plex Media Server.tar.gz"

# Stop plex from running so we can get a clean snapshot
systemctl stop plexmediaserver.service

# Take the snapshot
tar -zcpf "${DST}" "${SRC}"

# Start plex again, hopefully minimizing downtime
systemctl start plexmediaserver.service

# Adjust permissions so the snapshot is world-readable
chmod a+r "${DST}"
