#!/bin/bash -e

prepend_to_path()
{
    # Takes the path variable to prepend to, and then the new path
    if [ "${#}" -ne 2 ]; then
        return 1
    fi

    PATHVAR="${1}"
    NEWPATH="${2}"

    # Do nothing if NEWPATH is on the path already
    if echo "${!PATHVAR}" | grep "${NEWPATH}" > /dev/null; then
        return 0
    fi

    if [ -z "${!PATHVAR}" ]; then
        declare "${PATHVAR}=${NEWPATH}"
    else
        declare "${PATHVAR}=${NEWPATH}:${!PATHVAR}"
    fi
}
