#!/bin/bash

NUM_FAILED=0

# We'll have to come back here after each test
START_DIR=$(pwd)

for PATHNAME in $@; do

    echo -n "Running $PATHNAME ... "

    BNAME=$(basename "$PATHNAME")

    cd $(dirname "$PATHNAME")
    ./"$BNAME" > "$BNAME".out 2> "$BNAME".err

    # Did it work?
    if [ $? == 0 ]; then
        echo pass
    else
        echo FAILED!
        NUM_FAILED=$(($NUM_FAILED + 1))
    fi

    # Change eback to where we originally were
    cd "$START_DIR"
done

if [ "$NUM_FAILED" == 0 ]; then
    echo All tests pass
else
    echo "$NUM_FAILED tests failed"
fi

exit "$NUM_FAILED"
