#!/bin/bash

function displayhelp {
    echo "$0 [ --debug | --release ] [ --static | --shared ] [ --help ]"
}

DEBUG_SET=false
RELEASE_SET=false
STATIC_SET=false
SHARED_SET=false

DIRECTORY_SET=false
DIRECTORY=.

while [ -n "$1" ]
do
    case "$1" in
        -d | --debug)
            DEBUG_SET=true
            RELEASE_SET=false
            ;;

        -h | --help)
            displayhelp
            exit
            ;;

        -r | --release)
            RELEASE_SET=true
            DEBUG_SET=false
            ;;

        --staticlibs)
            STATIC_SET=true
            SHARED_SET=false
            ;;

        --sharedlibs)
            SHARED_SET=true
            STATIC_SET=false
            ;;

        *)
            # If we see something not explicitly recognized by this script stop
            # processing arguments and pass remaining arguments directly to
            # cmake
            break;
            ;;

    esac

    # We're done with the current argument, move to the next.
    shift
done

ARGS=

if [ $DEBUG_SET == true ]; then
    ARGS+='-DCMAKE_BUILD_TYPE=Debug'
elif [ $RELEASE_SET == true ]; then
    ARGS+='-DCMAKE_BUILD_TYPE=Release'
fi

ARGS+=' '

if [ $STATIC_SET == true ]; then
    ARGS+='-DBUILD_SHARED_LIBS=OFF'
elif [ $SHARED_SET == true ]; then
    ARGS+='-DBUILD_SHARED_LIBS=ON'
fi

ARGS+=" $@"

# Generate the makefile with cmake
cmake $ARGS
