#!/bin/bash

# Default arguments
ARGS="--enable=all --std=posix --inconclusive"

# Additionally define these arguments if run in Jenkins configuration (Jenkins
# cppcheck plugin only understands XML-formatted cppcheck output)
JENKINS_ARGS="--xml --xml-version=2 "
JENKINS_ARGS+=`cat .cppcheck-ignore | sed "s/.*/-i &/" | tr "\n" " "`

USE_JENKINS_ARGS=false

while [ -n "$1" ]
do
    case "$1" in
        -J)
            USE_JENKINS_ARGS=true
            ;;

        *)
            # If we see something not explicitly recognized by this script stop
            # processing arguments and pass remaining arguments directly to
            # cppcheck
            break
            ;;

    esac

    # We're done with the current argument, move to the next.
    shift
done

if [ "$USE_JENKINS_ARGS" == true ]; then
    ARGS+=" $JENKINS_ARGS"
fi

ARGS+=" $@"

cppcheck $ARGS
