#!/bin/bash

display_usage()
{
    echo "Usage: ${0} [-d | --debug] [-h | --help] [-r | --release] [--staticlibs] [--sharedlibs] PATH"
}

DEBUG_SET=false
RELEASE_SET=false
STATIC_SET=false
SHARED_SET=false

while [ -n "${1}" ]; do

    case "${1}" in

        -d | --debug)
            DEBUG_SET=true
            RELEASE_SET=false
            ;;

        -h | --help)
            display_usage
            exit 0
            ;;

        -r | --release)
            RELEASE_SET=true
            DEBUG_SET=false
            ;;

        --staticlibs)
            STATIC_SET=true
            SHARED_SET=false
            ;;

        --sharedlibs)
            SHARED_SET=true
            STATIC_SET=false
            ;;

        *)
            # If we see something not explicitly recognized by this script stop
            # processing arguments and pass remaining arguments directly to
            # cmake
            break;
            ;;

    esac

    # We're done with the current argument, move to the next.
    shift
done

ARGS=

if [ "${DEBUG_SET}" = true ]; then
    ARGS+='-DCMAKE_BUILD_TYPE=Debug'
elif [ "${RELEASE_SET}" = true ]; then
    ARGS+='-DCMAKE_BUILD_TYPE=Release'
fi

ARGS+=' '

if [ "${STATIC_SET}" = true ]; then
    ARGS+='-DBUILD_SHARED_LIBS=OFF'
elif [ "${SHARED_SET}" = true ]; then
    ARGS+='-DBUILD_SHARED_LIBS=ON'
fi

# Generate the makefile with cmake
cmake "${ARGS}" "${@}"
