#!/bin/bash

# Default arguments
ARGS="--enable=all --std=posix --inconclusive --force"

# Additionally define these arguments if run in Jenkins configuration (Jenkins
# cppcheck plugin only understands XML-formatted cppcheck output)
JENKINS_ARGS="--xml --xml-version=2 --inline-suppr "
JENKINS_ARGS+=`cat .cppcheck-ignore | sed "s/.*/-i &/" | tr "\n" " "`

CPPCHECK_XML=cppcheck-result.xml

JENKINS_MODE=false

while [ -n "$1" ]
do
    case "$1" in
        -J)
            JENKINS_MODE=true
            ;;

        *)
            # If we see something not explicitly recognized by this script stop
            # processing arguments and pass remaining arguments directly to
            # cppcheck
            break
            ;;

    esac

    # We're done with the current argument, move to the next.
    shift
done

if [ "$JENKINS_MODE" == true ]; then
    ARGS+=" $JENKINS_ARGS"
fi

ARGS+=" $@"

if [ "$JENKINS_MODE" == true ]; then
    cppcheck $ARGS 2> $CPPCHECK_XML
    ! grep -E '(severity="error"|severity="warning")' $CPPCHECK_XML > /dev/null
else
    cppcheck $ARGS
fi
