#!/bin/tcsh

# Reset this view back to default; gets rid of all view-private files, among
# other things
view-default

# Set build options
cd /vobs/aircraft++
build-default
build-models bat4
build-plugins serialportparser matlab2010a
build-buildoption PRODUCTION

# Actually run the build
kw-nightly Bat4 "clearmake -B ~/.bldhost.jedi.ndc.nasa.gov -V sim"
kw-sync Bat4 LaSRS_Core
kw-sync Bat4 GenericUav
