#!/bin/tcsh

# Reset this view back to default; gets rid of all view-private files, among
# other things
view-default

# Set build options
cd /vobs/lasrs++/Dds/redist
build-default
build-buildoption PRODUCTION
build-ddsimplementation OPEN_SPLICE

# Actually run the build
kw-nightly DDS_Redistributable_OpenSplice "make -B"
kw-sync DDS_Redistributable_OpenSplice LaSRS_Core
kw-sync DDS_Redistributable_OpenSplice DDS_Redistributable_Connext
