#!/bin/bash

VIEW=
VIEW_SET=false

KW_SET=false

NIGHTLY=
NIGHTLY_SET=false

while [ -n "$1" ]
do
    case "$1" in

        -v | --view)
            VIEW_SET=true
            VIEW="$2"
            shift
            ;;

        -k)
            KW_SET=true
            ;;

        *)
            NIGHTLY="$*"
            NIGHTLY_SET=true
            break
            ;;
    esac

    # We're done with the current argument, move to the next.
    shift
done

BUILD_CMD=runbuild
if [ "$KW_SET" == true ]; then
    BUILD_CMD=runkwbuild
fi

if [ "$VIEW_SET" == "true" ]; then
    cleartool setview -exec "$BUILD_CMD $NIGHTLY" "$VIEW" > /dev/null 2> /dev/null
else
    "$BUILD_CMD" "$NIGHTLY" > /dev/null 2> /dev/null
fi
