#!/bin/bash

TMP_MAKEFILEOPTIONS=/tmp/$USER.makefile.options

# Grab the DDS implementation
DDS_IMPLEMENTATION=$@

if ! [ -e Makefile.options ]; then

    # Initialize a Makefile.options
    build-default
fi

# Make the change to a temporary file
cat Makefile.options | setmkopts --ddsimplementation $DDS_IMPLEMENTATION > $TMP_MAKEFILEOPTIONS

# Overwrite the Makefile.options proper with the new one
mv $TMP_MAKEFILEOPTIONS Makefile.options
