#!/bin/bash

if [ -z $1 ]; then
    echo "You have to specify a build option."
    exit
fi

# Grab the build option
BUILDOPTION=$1

# Convert to uppercase characters
BUILDOPTION=`echo $BUILDOPTION | tr '[:lower:]' '[:upper:]'`

# Make the change to a temporary file
cat Makefile.options | setmkopts --buildoption $BUILDOPTION > Makefile.options.$$

# Overwrite the Makefile.options proper with the new one
mv Makefile.options.$$ Makefile.options
