#!/bin/bash

# Grab the DDS implementation
DDS_IMPLEMENTATION=$@

if ! [ -e Makefile.options ]; then

    # Initialize a Makefile.options
    build-default
fi

# Make the change to a temporary file
cat Makefile.options | setmkopts --ddsimplementation $DDS_IMPLEMENTATION > Makefile.options.$$

# Overwrite the Makefile.options proper with the new one
mv Makefile.options.$$ Makefile.options
