#!/bin/bash

# Grab the list of models
MODELS=$@

# Replace spaces with commas as required by setmkopts
MODELS=${MODELS// /,}

if ! [ -e Makefile.options ]; then

    # Initialize a Makefile.options
    build-default
fi

# Make the change to a temporary file
cat Makefile.options | setmkopts --modellist=$MODELS > Makefile.options.$$

# Overwrite the Makefile.options proper with the new one
mv Makefile.options.$$ Makefile.options
