#!/bin/bash

if [ -z $1 ]; then
    echo "You have to specify an osg option."
    exit
fi

# Grab the osg option
OSGOPTION=$1

# Convert to uppercase characters
OSGOPTION=`echo $OSGOPTION | tr '[:lower:]' '[:upper:]'`

# Make the change to a temporary file
cat Makefile.options | setmkopts --osgoption $OSGOPTION > Makefile.options.$$

# Overwrite the Makefile.options proper with the new one
mv Makefile.options.$$ Makefile.options
