#!/bin/bash

if [ -z $1 ]; then
    echo "You have to specify a gui option."
    exit
fi

# Grab the gui option
GUIOPTION=$1

# Convert to uppercase characters
GUIOPTION=`echo $GUIOPTION | tr '[:lower:]' '[:upper:]'`

# Make the change to a temporary file
cat Makefile.options | setmkopts --guioption $GUIOPTION > Makefile.options.temp

# Overwrite the Makefile.options proper with the new one
mv Makefile.options.temp Makefile.options
