#!/bin/bash

if [ -z "$1" ]; then
    echo "What branch should I add?"
    exit
fi

# cleartool setcs won't take a stream so the default cs has to go to a file first
TMP_CS=/tmp/$USER.cs

# Generate the new line
ADDBRANCH=`gencsline $1`

cleartool catcs | \
sed "s:CHECKEDOUT:CHECKEDOUT\\n$ADDBRANCH:" > $TMP_CS

cleartool setcs $TMP_CS
