#!/bin/bash

# cleartool setcs won't take a stream so the default cs has to go to a file first
TMP_CS=/tmp/$USER.cs

if [ -z "$1" ]; then
   echo "Lines corresponding to which branch should be modified?"
   exit
elif [ -z "$2" ]; then
    echo "What should the mkbranch option be set to?"
    exit
fi

cleartool catcs | sed "s:$1.*:$1 -mkbranch $2:" > $TMP_CS

cleartool setcs $TMP_CS
